config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :destinations

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'destinations' => 'destinations#index'

  root 'welcome#index'
end

app/models/destination.rb
class Destination < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	geocoded_by :address
	after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json

  def index
    if params[:country] == nil
      @destinations = Destination.all
    else @destinations = Destination.where(country: params[:country].titleize)
    end
    @my_countries = Destination.select(:country).order(:country).distinct
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar, :latitude, :longitude, :address)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = 'United States'
  	@countries = ['Brazil', 'Thailand', 'Italy']
  	@images = ['plane.png', 'brazil.jpg', 'thailand.jpg', 'venice.jpg'].shuffle
  	@united_states = {'capital-city' => 'Fresno', 'favorite_city' => 'Venice Beach', 
  		'favorite_state' => 'California', 'flag_colors' => ['red', 'white']}
  end

  def about
  	@color = params[:color]
  	@size = params[:size]
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>

  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>


      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, placeholder: 'A place', class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control" %>
  </div>

  <div class= "field form-group">
    <%= f.label :population %><br>
    <%= f.number_field :population, class: "form-control" %>
  </div>

  <div class="field form-group">
  <%= f.label :address %><br>
  <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>

   <div class="field form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'Photo' %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<!-- <% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %> -->

<p id="notice"><%= notice %></p>


<ul class="nav nav-pills" role = "tablist">
  <li><%= link_to "all", destinations_path %></li>
  <% @my_countries.each do |c| %>
  <li><%= link_to "#{c.country}", controller: "destinations", country: "#{c.country}" %></li>
  <% end %>
  </ul>


<h1>Listing Destinations</h1>



<div class = 'row'>

    <% @destinations.each do |destination| %>

    <div class = 'col-md-4'>

      <div class = 'panel panel-default'>

        <div class = 'panel-body'>

          <h2><%= destination.city %></h2>
          <h3><%= destination.country %></h3>
          <p>Population: <%= destination.population %></p>
          <%= image_tag destination.avatar.url(:medium), class: "img-responsive" %>
          <p><%= destination.description %></p>
          <%= link_to 'Show', destination, class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_destination_path(destination), class: 'btn btn-default' %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </div>
      </div>
    </div>

    <% end %>

</div>



<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>


  <h1><%= @destination.city %>, <%= @destination.country %></h1>
  <%= image_tag @destination.avatar.url(:medium) %>
	<h2>Population <%= @destination.population %></h2>

  <h1><%= @destination.address %></h1>

  <p><%= @destination.latitude %>, <%= @destination.longitude %></p>

  <p><%= @destination.description %></p>

  <div id="destination-map"></div>

<div class='btn-group'>
<%= link_to 'Edit', edit_destination_path(@destination), class: 'btn btn-default' %>
<%= link_to 'Back', destinations_path, class: 'btn btn-default' %>
</div>

<%= javascript_tag do %>
   latitude = '<%= j @destination.latitude.to_s %>';
   longitude = '<%= j @destination.longitude.to_s %>';
   address = '<%= j @destination.address %>';
   description = '<%= j @destination.description %>';
<% end %>

app/views/layouts/_nav.html.erb
	<nav class="navbar navbar-default">
  	<div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

    	<div class="navbar-header">
        
      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
      	</button>

<!-- navbar brand -->

      <%= link_to "Travel", root_path, class: "navbar-brand" %>

      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      	<ul class="nav navbar-nav">
        	<li><%= link_to "About", about_path %></li>
        	<li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Destinations", destinations_path %></li>

<!--  left dropdown menu -->

        	<!-- <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>

        </li> -->

      </ul>

<!-- search form -->

      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

<!-- right navbar -->

      <ul class="nav navbar-nav navbar-right">

        <li><a href="#">Link</a></li>

<!-- right nav dropdown -->

    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% end %>

      	</ul>

    	</div><!-- /.navbar-collapse -->
  	</div><!-- /.container-fluid -->

	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <title>TravelApp</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>

  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lobster"%>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Noto+Sans"%>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>

  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>">
  </script>

  <%= csrf_meta_tags %>

</head>

<body>

<!--   renders nav bar from partial in layouts -->

<%= render 'layouts/nav' %>

	<div class ='container'>
		<%= yield %>
	</div>

</body>

</html>

app/views/welcome/about.html.erb
<style>
  body {
    background: <%= @color %>;
  }
</style>


<h1>About this Travel App</h1>

<h2>All about it.</h2>

<p>My favorite color is <%= @color %></p>

<p>My shoe size is <%= @size %></p>

<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>

<%= link_to "Red", about_path(color: "red"), class: "btn btn-danger" %>

app/views/welcome/contact.html.erb
<div class="meat">
<h1>Contact</h1>

<h3>Today I learned this is a real place, tho more lush than the OC. I've made a huge tiny mistake.</h3>

<p>I think the only time you cooked for us was the morning Rosa's mom died. You gave us cereal in an ashtray. These are my awards, Mother. From Army. The seal is for marksmanship, and the gorilla is for sand racing. It's as Ann as the nose on plain's face. Hey, it was one night of wild passion! And yet you didn't notice her body? I like to look in the mirror. If mother sees this, she will blow a cow. I hear the jury's still out on science. I know she's a brownish area! With points! And I love her! If this tableau I recreate, perhaps I can re-snare my mate.</p>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to this Great Travel Site</h1>

<h2>This is my very awesome travel site.</h2>

<h3><%= @homeland %></h3>

<ul>
<% @countries.each do |country| %>
	<li><%= country %></li>
<% end %>
</ul>

<table class="table">
  <tr>
    <% @united_states.each do |key,value| %>
	  <th><%= key.titleize %></th>
    <% end %>
  </tr>
  <tr>
    <% @united_states.each do |key,value| %>
<!--     .kind_of? checks the value of the argument   -->
      <% if value.kind_of?(Array) %>
<!--       .join would show the values of the array with no commas -->
          <td><%= value.join(", ") %></td>
<!--           else statement is only for if it's not an array -->
      <% else %>
         <td><%= value %></td>
      <% end %>
    <% end %>
  </tr>
</table>


<% @images.each do |photo| %>
  <%= image_tag photo, class: "img-responsive" %>
<% end %>

<div id="map-canvas"></div>